name: venv
dependencies:
  - python>=3.8
  - pip:
    - finnhub-python==2.4.7
    - certifi==2021.10.8
    - charset-normalizer==2.0.9
    - cycler==0.11.0
    - fonttools==4.28.5
    - idna==3.3
    - matplotlib==3.5.1
    - numpy==1.21.5
    - packaging==21.3
    - pandas==1.3.5
    - pandas-ta==0.3.14b0
    - Pillow==9.0.0
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pytz==2021.3
    - six==1.16.0
    - urllib3==1.26.7
    - yfinance==0.1.74
    - mypy==0.971
    - mypy-extensions==0.4.3
    - celery==5.2.7
